# Generated by Django 4.0.5 on 2022-06-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='%m/%d/%Y'),
        ),
    ]
