# Generated by Django 4.0.5 on 2022-06-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0002_alter_familiar_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
